name: mymovieapp
description: A new Flutter project.

# Define la versión y el rango del SDK de Dart compatible con null-safety.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencias actualizadas a versiones compatibles con null-safety.
  cupertino_icons: ^1.0.5
  carousel_slider: ^5.1.1
  intl: ^0.18.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Asegúrate de que el archivo de imagen esté en la carpeta correcta.
  assets:
    - assets/nobody.jpg
